name: PHP Composer

on:
  push:
    branches: [ "main", "refactoring-tennis" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      working-directory: ./tennis

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: tennis/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: ./tennis

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer tests
      working-directory: ./tennis
